# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

#if ! echo $TERM | egrep "*256color*" > /dev/null
#then
#  TERM=`echo "$TERM-256color"`
#fi
#
{% if username == "vagrant" %}TERM="xterm-256color"{% endif %}

# Path to alias file
ALIASES=$HOME/.zshaliases

# vi-like keybindings
set -o vi

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"
# ZSH_THEME="rachel"

if [[ -f $ALIASES ]]
then
  source $ALIASES
fi


if [[ -f /usr/share/dict/words ]] 
then
  export DICT="/usr/share/dict/words"
elif [[ -f /usr/share/dict/cracklib-small ]]
then
  export DICT="/usr/share/dict/cracklib-small"
fi

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
plugins=(git)

source $ZSH/oh-my-zsh.sh

export GOPATH="$HOME/dev/go"

# Customize to your needs...
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/core_perl:$GOPATH/bin

export EDITOR="vim"

# VIM gruvbox colour scheme
$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh

# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
