" Required for Vundle
set nocompatible
filetype off

" Initialise Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Required to be at the top
Plugin 'gmarik/Vundle.vim'

" Utilities
Plugin 'airblade/vim-gitgutter'
Plugin 'majutsushi/tagbar'
Plugin 'oplatek/Conque-Shell'
Plugin 'rhysd/committia.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-scripts/buftabs'
Plugin 'vim-scripts/taglist.vim'
Plugin 'wincent/Command-T'
Plugin 'Yggdroot/indentLine'

" Syntax highlighting
Plugin 'chrisbra/csv.vim'
Plugin 'derekwyatt/vim-scala'
Plugin 'fatih/vim-go'
Plugin 'groenewege/vim-less'
Plugin 'plasticboy/vim-markdown'
Plugin 'solarnz/thrift.vim'

" Color schemes
Plugin 'Lokaltog/vim-distinguished'
Plugin 'morhetz/gruvbox'
Plugin 'nanotech/jellybeans.vim'
Plugin 'quanganhdo/grb256'
Plugin 'tomasr/molokai'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-scripts/calmar256-lightdark.vim'
Plugin 'vim-scripts/mrkn256.vim'
Plugin 'vim-scripts/xoria256.vim'
call vundle#end()

" Colours
set background=dark
silent!color gruvbox

" Aesthetics
" Syntax highlighting
syntax on
set hlsearch
set incsearch
set showmatch

" Default indentation
set shiftwidth=4
set tabstop=4
set expandtab
filetype plugin indent on

" Fixes that weird behaviour with backspace
" http://vim.wikia.com/wiki/Backspace_and_delete_problems
set backspace=2

" Line numbers and highlighting
set number
set relativenumber
set cursorline

" For the lols
set titlestring=%r%m\ %t\ %y\ -\ VIM:\ because\ nano\ is\ for\ pussies titlelen=80

" Syntastic
" let g:syntastic_go_checkers = ['go', 'golint', 'govet']
let g:syntastic_go_checkers = ['go', 'govet']

" Show whitespace
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

" Tagbar
nmap <F8> :TagbarToggle<CR>

" Airline tweaks
set laststatus=2 " Fixes airline not being visibile without split
let g:airline_powerline_fonts=1
let g:airline_interactive_collapse=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#=1
let g:airline_theme='ubaryd'
" set fillchars+=stl:\ ,stlnc:\

" Discourage use of mouse and keyboard
set mouse=""
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

